# Generated by Django 5.1.4 on 2024-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='link',
            field=models.CharField(max_length=128, verbose_name='Link'),
        ),
    ]
