# Generated by Django 4.2.17 on 2024-12-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_socialmedia_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Enter the subtitle of the post.', max_length=512, null=True, verbose_name='Subtitle'),
        ),
    ]
