# Generated by Django 4.2.17 on 2024-12-20 07:49

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_column', django_summernote.fields.SummernoteTextField(blank=True, null=True, verbose_name='First Column')),
                ('second_column', django_summernote.fields.SummernoteTextField(blank=True, null=True, verbose_name='Second Column')),
                ('third_column', django_summernote.fields.SummernoteTextField(blank=True, null=True, verbose_name='Third Column')),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickinfo', to='blog.preference', verbose_name='Preference')),
            ],
            options={
                'verbose_name': 'Quick Info',
                'verbose_name_plural': 'Quick Info',
            },
        ),
    ]
