# Generated by Django 4.2.17 on 2024-12-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_quickinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickInfo',
        ),
    ]
