# Generated by Django 5.1.4 on 2024-12-17 16:29

import django.db.models.deletion
import django_summernote.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('english_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Department Name (English)')),
                ('date_establish', models.DateField(blank=True, null=True)),
                ('legality_number', models.CharField(blank=True, max_length=32, null=True)),
                ('date_legality', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('grade', models.CharField(choices=[('6', 'SMA / sederajat'), ('20', 'D1'), ('21', 'D2'), ('22', 'D3'), ('23', 'D4'), ('30', 'S1'), ('31', 'Profesi'), ('32', 'Sp-1'), ('35', 'S2'), ('36', 'S2 Terapan'), ('37', 'Sp-2'), ('40', 'S3'), ('41', 'S3 Terapan')], default='30', max_length=32)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('english_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Faculty Name (English)')),
                ('date_establish', models.DateField(blank=True, null=True)),
                ('legality_number', models.CharField(blank=True, max_length=32, null=True)),
                ('date_legality', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sister_api', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15, verbose_name='Sister API')),
                ('sevima_api', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15, verbose_name='Sevima API')),
            ],
            options={
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preference',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, help_text='Brief description of the scholarship', null=True, verbose_name='Description')),
                ('types', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image (JPG, PNG, JPEG)'), ('both', 'PDF and Image')], default='both', max_length=30, verbose_name='Types')),
                ('max_size', models.IntegerField(default=1000, verbose_name='Max Size (Kb)')),
            ],
            options={
                'verbose_name': 'Scholarship Attachment',
                'verbose_name_plural': 'Scholarship Attachments',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, help_text='Brief description of the scholarship', null=True, verbose_name='Description')),
                ('requirement', django_summernote.fields.SummernoteTextField(blank=True, help_text='Requirement for proposing the scholarship', null=True, verbose_name='Requirement')),
                ('status', models.CharField(choices=[('on-going', 'On Going'), ('coming-soon', 'Coming Soon'), ('closed', 'Closed')], default='coming-soon', max_length=30, verbose_name='Scholarship Status')),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Whether the scholarship is internal or external', max_length=30, verbose_name='Scholarship Source')),
                ('destination', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Destination of scholarship funds', max_length=30, verbose_name='Scholarship Destination')),
                ('target_audience', models.CharField(choices=[('new-student', 'New Student'), ('active-student', 'Active Student'), ('graduated-student', 'Graduated Student')], default='active-student', help_text='Who is eligible for this scholarship', max_length=30, verbose_name='Target Audience')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('quota', models.PositiveIntegerField(help_text='Number of recipients available', verbose_name='Quota')),
                ('departments', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarship.department', verbose_name='Departments')),
                ('faculties', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarship.faculty', verbose_name='Faculties')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('note', django_summernote.fields.SummernoteTextField(blank=True, null=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Application Status')),
                ('reviewers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarship.scholarship', verbose_name='Scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'verbose_name_plural': 'Scholarship Applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('recommended_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20, null=True, verbose_name='Recommended Status')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='Review Comment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='scholarship.scholarshipapplication')),
            ],
            options={
                'verbose_name': 'Application Review',
                'verbose_name_plural': 'Application Reviews',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='scholarship_applications/files/', verbose_name='File')),
                ('url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scholarship.scholarshipapplication', verbose_name='Scholarship Application')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_attachments', to='scholarship.scholarshipattachment', verbose_name='Attachment Type')),
            ],
            options={
                'verbose_name': 'Application Attachment',
                'verbose_name_plural': 'Application Attachments',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAttachmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_requirements', to='scholarship.scholarshipattachment', verbose_name='Attachment')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_requirements', to='scholarship.scholarship', verbose_name='Scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship Attachment Requirement',
                'verbose_name_plural': 'Scholarship Attachment Requirements',
            },
        ),
        migrations.AddField(
            model_name='scholarship',
            name='attachments',
            field=models.ManyToManyField(related_name='attachments', through='scholarship.ScholarshipAttachmentRequirement', to='scholarship.scholarshipattachment', verbose_name='Attachments'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('student_id', models.CharField(max_length=12, verbose_name='Student ID')),
                ('sex', models.CharField(blank=True, choices=[('L', 'Male'), ('P', 'Female')], max_length=11, null=True, verbose_name='Sex')),
                ('status', models.CharField(choices=[('A', 'Aktif'), ('BY', 'Belum Yudisium'), ('C', 'Cuti'), ('D', 'Drop Out / Dikeluarkan'), ('G', 'Sedang Double Degree'), ('H', 'Menghilang / Tanpa Kabar'), ('K', 'Mengundurkan Diri / Keluar'), ('KM', 'Kampus Merdeka'), ('L', 'Lulus'), ('LL', 'Lainnya'), ('N', 'Non Aktif'), ('P', 'Putus Studi'), ('PO', 'Gugur Studi / Passing Out'), ('T', 'Transfer / Pindah'), ('U', 'Menunggu Ukom'), ('W', 'Wafat')], default='A', max_length=11, verbose_name='Status')),
                ('source', models.CharField(choices=[('sevima', 'Sevima'), ('sister', 'Sister'), ('manual', 'Manual')], default='sevima', max_length=11, verbose_name='Source')),
                ('religion', models.CharField(choices=[('1', 'Islam'), ('2', 'Kristen'), ('3', 'Khatolik'), ('4', 'Hindu'), ('5', 'Budha'), ('6', 'Konghucu'), ('7', 'Lain-lain')], default='1', max_length=3, verbose_name='Religion')),
                ('place_birth', models.CharField(max_length=64, verbose_name='Place of Birth')),
                ('date_birth', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, help_text='Write complete address', null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Postal code')),
                ('university_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='University E-mail')),
                ('mobile_number', models.CharField(blank=True, help_text='Number must be always active', max_length=17, null=True, verbose_name='Mobile Number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarship.student', verbose_name='Student'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id_unit', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('shortname', models.CharField(max_length=32, verbose_name='Shortname')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scholarship.unit', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('english_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Office Name (English)')),
                ('date_establish', models.DateField(blank=True, null=True)),
                ('legality_number', models.CharField(blank=True, max_length=32, null=True)),
                ('date_legality', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.unit')),
            ],
            options={
                'verbose_name': 'Office',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.unit'),
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.unit'),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('english_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='University Name (English)')),
                ('date_establish', models.DateField(blank=True, null=True)),
                ('legality_number', models.CharField(blank=True, max_length=32, null=True)),
                ('date_legality', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.unit')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
