# Generated by Django 5.1.4 on 2024-12-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_reviewer_alter_applicationreview_reviewer'),
        ('worldmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worldmap.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worldmap.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='student',
            name='regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worldmap.regency', verbose_name='Regency'),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worldmap.village', verbose_name='Village'),
        ),
    ]
