# Generated by Django 5.1.4 on 2024-12-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_student_district_student_province_student_regency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='reviewers',
        ),
    ]
