# Generated by Django 5.1.4 on 2024-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_remove_scholarship_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=21, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Scholarship Status',
                'verbose_name_plural': 'Scholarship Status',
            },
        ),
        migrations.AddField(
            model_name='scholarship',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='scholarship.scholarship', verbose_name='Targets'),
        ),
    ]
