# Generated by Django 5.1.4 on 2024-12-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_scholarshiptarget_scholarship_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='scholarship.scholarshiptarget', verbose_name='Targets'),
        ),
    ]
