# Generated by Django 5.1.4 on 2024-12-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_alter_scholarship_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='scholarships/thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
